"""add usage tracking to users

Revision ID: 3e87d5a1d0ec
Revises: 26fcb3c4adad
Create Date: 2026-09-04 09:33:26.006322

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e87d5a1d0ec'
down_revision: Union[str, Sequence[str], None] = '26fcb3c4adad'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('plan', sa.String(), nullable=True))
    op.add_column('users', sa.Column('message_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('usage_reset_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE users SET plan = 'free' WHERE plan IS NULL")
    op.execute("UPDATE users SET message_count = 0 WHERE message_count IS NULL")
    op.execute("UPDATE users SET usage_reset_at = now() + interval '30 days' WHERE usage_reset_at IS NULL")

    op.alter_column('users', 'plan', nullable=False)
    op.alter_column('users', 'message_count', nullable=False)

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'usage_reset_at')
    op.drop_column('users', 'message_count')
    op.drop_column('users', 'plan')
    # ### end Alembic commands ###
