"""add paystack customer and subscription codes

Revision ID: 8d2c5a121817
Revises: 9a833563f0a8
Create Date: 2026-09-30 22:37:01.204870

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2c5a121817'
down_revision: Union[str, Sequence[str], None] = '9a833563f0a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'refresh_tokens', ['token'])
    op.add_column('users', sa.Column('paystack_customer_code', sa.String(), nullable=True))
    op.add_column('users', sa.Column('paystack_subscription_code', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'users', ['paystack_customer_code'])
    op.create_unique_constraint(None, 'users', ['paystack_subscription_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'paystack_subscription_code')
    op.drop_column('users', 'paystack_customer_code')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    # ### end Alembic commands ###
