"""add email_verified to users

Revision ID: a163442e0c75
Revises: 3e87d5a1d0ec
Create Date: 2026-09-12 10:44:26.480999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a163442e0c75'
down_revision: Union[str, Sequence[str], None] = '3e87d5a1d0ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.execute("UPDATE users SET email_verified = false WHERE email_verified IS NULL")
    op.alter_column('users', 'email_verified', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    # ### end Alembic commands ###
