"""switch usage tracking to token-based rolling window

Revision ID: f1cffb1d0471
Revises: a9d2c26feac5
Create Date: 2026-09-17 11:50:40.841493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f1cffb1d0471'
down_revision: Union[str, Sequence[str], None] = 'a9d2c26feac5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('users', sa.Column('token_count', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('window_started_at', sa.DateTime(), nullable=True))

    op.execute("UPDATE users SET token_count = 0 WHERE token_count IS NULL")
    op.execute("UPDATE users SET window_started_at = now() WHERE window_started_at IS NULL")

    op.alter_column('users', 'token_count', nullable=False)
    op.alter_column('users', 'window_started_at', nullable=False)

    op.drop_column('users', 'message_count')
    op.drop_column('users', 'usage_reset_at')

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('usage_reset_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('message_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'window_started_at')
    op.drop_column('users', 'token_count')
    # ### end Alembic commands ###
